### ISSUE TITLE
sl7_gallery_album module missing

### ISSUE THREAD

**Issue by prosp** [SemyonDragunov/sl7_gallery#1]
The module won't work. Upon editing a gallery or adding an image the following error message is being displayed: "User warning: The following module is missing from the file system: sl7_gallery_album. For information about how to fix this, see the documentation page. in _drupal_trigger_error_with_delayed_logging() (line 1143 of /home/serge/data/www/serge.debigreen/includes/bootstrap.inc)."

What is that "sl7_gallery_album" module? Where can I get it?

**Comment by prosp** [comment]
Correction: it does work but it does not show the added images at once. And this warning is annoying.

**Comment by semyondragunov** [comment]
I'll deal with the error later.
For fix error message: https://www.drupal.org/project/module_missing_message_fixer
